### ISSUE TITLE
Export the sample file as a diagram

### ISSUE THREAD

**Issue by calumtomeny** [ContextMapper/web-ide-demo#1]
After opening the Gitpod Web IDE demo, what are the steps to generate an image of the sample cml file?

**Comment by stefan-ka** [comment]
Hi @calumtomeny 

Open the `*.cml` file and use the context menu:

![image](https://user-images.githubusercontent.com/6763278/117295003-9b9a8800-ae73-11eb-8c55-e8d30e5154a7.png)

Depending on which diagrams you want to generate you can use the context menu entries "Generate Graphical Context Map", "Generate PlantUML Diagrams", etc... The diagrams are always generated into the `src-gen` folder. In case you generate PlantUML, we generate `*.puml` files and you have to use the PlantUML plugin to generate the graphics.

Did this help? ;)

Best regards,
Stefan

**Comment by calumtomeny** [comment]
Hi @stefan-ka - that's perfect, thanks for the information.

**Comment by stefan-ka** [comment]
You are welcome, @calumtomeny :)

(I assume I can close this one; re-open it otherwise)
